# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_guid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=14)),
                ('email_address', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_id', models.IntegerField()),
                ('client_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataChangeLog',
            fields=[
                ('scn', models.IntegerField(primary_key=True, serialize=False)),
                ('connection_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Client')),
                ('scn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_guid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mileage_frequency', models.IntegerField()),
                ('duration_frequency', models.DurationField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('scn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('transaction_guid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('mileage', models.IntegerField()),
                ('date', models.DateField()),
                ('client_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Client')),
                ('scn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog')),
                ('service_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('client_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Client')),
                ('scn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog')),
            ],
        ),
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_service_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shop_service_time', models.DurationField()),
                ('client_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Client')),
                ('scn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog')),
                ('service_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_guid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('scn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Vehicle'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='vehicle_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Vehicle'),
        ),
        migrations.AddField(
            model_name='clienttype',
            name='scn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.ClientType'),
        ),
        migrations.AddField(
            model_name='client',
            name='scn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.DataChangeLog'),
        ),
    ]
