# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopservice',
            name='client_id',
        ),
        migrations.AddField(
            model_name='shopservice',
            name='shop_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='maintenancemanager.Shop'),
        ),
    ]
